### ISSUE TITLE
内网部署文档库

### ISSUE THREAD

**Issue by xinsir88** [kubeovn/docs#109]
大佬好，因为我们公司内网没有互联网，所有想把咱们得帮助文档搬到我们内网，我该如何操作呢？ 有没有类似k8s的官方文档的website那种的服务， 一下直接搞过去呢？求指导。
参考了https://github.com/kubeovn/docs 里面 .github 下的 workflow目录下的ci.yaml文件，但是没有太好的部署思路，能不能指导下呢？

**Comment by oilbeater** [comment]
参考 https://github.com/kubeovn/docs#readme
