### ISSUE TITLE
Missing context on Fixed Addresses page

### ISSUE THREAD

**Issue by SuniAve** [kubeovn/docs#51]
https://github.com/kubeovn/docs/blob/8e9e50c1cb9e8e1e6c0408891651dc382ce6b9d3/docs/guide/static-ip-mac.en.md?plain=1#L123

what is the needed configuration here?

**Comment by oilbeater** [comment]
@SuniAve Thanks for finding this issue. From v1.11 this feature is enabled by default. For previous version you should change the `keep-vm-ip` args in `kube-ovn-controller` to true.
