### ISSUE TITLE
Add English version for some advanced usage docs

### ISSUE THREAD

**Issue by shane965** [kubeovn/docs#90]
I have found that the following topics are not available in English:

* 使用 eBPF 加速节点内 TCP 通信
* Cilium NetworkPolicy 支持
* Cilium 网络流量观测

You can find the original documentation at https://kubeovn.github.io/docs/v1.12.x/en/advance/multi-nic/.

@oilbeater ,have you considered adding an English version of these documents? If there is no suitable candidate, you can let me do it.

**Comment by oilbeater** [comment]
@shane965 Thanks, just go ahead
